"""init core tables

Revision ID: c94893e4f345
Revises:
Create Date: 2026-05-21 14:28:03.763921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c94893e4f345"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("quota_limit", sa.Integer(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("lock_until", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "expression_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dataset_name", sa.String(length=128), nullable=False),
        sa.Column("file_format", sa.String(length=16), nullable=False),
        sa.Column("source_file_path", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("cell_count", sa.Integer(), nullable=False),
        sa.Column("gene_count", sa.Integer(), nullable=False),
        sa.Column("qc_status", sa.String(length=16), nullable=False),
        sa.Column("preprocess_status", sa.String(length=16), nullable=False),
        sa.Column("feature_dim", sa.Integer(), nullable=False),
        sa.Column("embedding_methods", sa.JSON(), nullable=False),
        sa.Column("deleted_flag", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expression_metadata_owner_user_id"),
        "expression_metadata",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "ann_indices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("index_name", sa.String(length=128), nullable=False),
        sa.Column("index_type", sa.String(length=32), nullable=False),
        sa.Column("metric_type", sa.String(length=16), nullable=False),
        sa.Column("params_json", sa.JSON(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("build_status", sa.String(length=16), nullable=False),
        sa.Column("publish_status", sa.String(length=16), nullable=False),
        sa.Column("recall_score", sa.Float(), nullable=False),
        sa.Column("memory_cost_mb", sa.Float(), nullable=False),
        sa.Column("is_loaded", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["expression_metadata.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ann_indices_dataset_id"), "ann_indices", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_ann_indices_owner_user_id"),
        "ann_indices",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "cell_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("cell_id", sa.String(length=128), nullable=False),
        sa.Column("cell_type", sa.String(length=64), nullable=True),
        sa.Column("organ", sa.String(length=64), nullable=True),
        sa.Column("sample_id", sa.String(length=64), nullable=True),
        sa.Column("obs_ext", sa.JSON(), nullable=False),
        sa.Column("qc_flags", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["expression_metadata.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cell_metadata_cell_id"), "cell_metadata", ["cell_id"], unique=False
    )
    op.create_index(
        op.f("ix_cell_metadata_dataset_id"),
        "cell_metadata",
        ["dataset_id"],
        unique=False,
    )
    op.create_table(
        "cell_vectors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("cell_id", sa.String(length=128), nullable=False),
        sa.Column("vector_type", sa.String(length=32), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("vector_blob", sa.LargeBinary(), nullable=False),
        sa.Column("norm_value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["expression_metadata.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cell_vectors_cell_id"), "cell_vectors", ["cell_id"], unique=False
    )
    op.create_index(
        op.f("ix_cell_vectors_dataset_id"), "cell_vectors", ["dataset_id"], unique=False
    )
    op.create_table(
        "search_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("index_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("result_path", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.String(length=64), nullable=True),
        sa.Column("finished_at", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["expression_metadata.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["index_id"], ["ann_indices.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_search_tasks_dataset_id"), "search_tasks", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_search_tasks_owner_user_id"),
        "search_tasks",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_search_tasks_task_id"), "search_tasks", ["task_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_tasks_task_id"), table_name="search_tasks")
    op.drop_index(op.f("ix_search_tasks_owner_user_id"), table_name="search_tasks")
    op.drop_index(op.f("ix_search_tasks_dataset_id"), table_name="search_tasks")
    op.drop_table("search_tasks")
    op.drop_index(op.f("ix_cell_vectors_dataset_id"), table_name="cell_vectors")
    op.drop_index(op.f("ix_cell_vectors_cell_id"), table_name="cell_vectors")
    op.drop_table("cell_vectors")
    op.drop_index(op.f("ix_cell_metadata_dataset_id"), table_name="cell_metadata")
    op.drop_index(op.f("ix_cell_metadata_cell_id"), table_name="cell_metadata")
    op.drop_table("cell_metadata")
    op.drop_index(op.f("ix_ann_indices_owner_user_id"), table_name="ann_indices")
    op.drop_index(op.f("ix_ann_indices_dataset_id"), table_name="ann_indices")
    op.drop_table("ann_indices")
    op.drop_index(
        op.f("ix_expression_metadata_owner_user_id"), table_name="expression_metadata"
    )
    op.drop_table("expression_metadata")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
